### ISSUE TITLE
`character-logistic-slots` and `character-logistic-trash-slots` counts

### ISSUE THREAD

**Issue by OvermindDL1** [msakuta/Factorio-LateUpgrades-Mod#2]
I've noticed the higher `character-logistic-slots` researches go up in 2, which is great, however it seems to end at `38` for its maximum value if I count correctly.  Might be good to lower its max to 26 to make it an even 30 so it will finish with a full row in the inventory or to raise it to 31 to make it an even 40.

Same with `character-logistic-trash-slots` except it needs to be increased by 2 more, so its max should be 27 to make an even row if I count correctly.

**Comment by msakuta** [comment]
At the highest level (25), the number of character's logistic slots ends at 68, because level 1 through 6 increases the modifier by 5.

![image](https://cloud.githubusercontent.com/assets/2798715/16909069/0d20d750-4c9e-11e6-88e3-732bee1f1923.png)

Honestly, I didn't even worry about actually reaching the max level :)
It should take hundreds of hours to finish it all, which is the point. But yeah, increasing the max by 1 won't hurt. I'll think about  that.

**Comment by OvermindDL1** [comment]
I have a server going with friends and even with the Science Overhaul mod (which makes the requires research fairly _extreme_ on the settings we use, for everything) we have finished researching everything (took a few weeks).  So if you think something cannot be reached, it can.  ^.^

**Comment by msakuta** [comment]
OK, there's actually another problem with this. In 1080p resolution, when I maxed the researches by cheating, the logistic slots expanded to the point it overlaps with toolbelt, so I couldn't swap the items between the inventory and toolbelt (unless moving the inventory window away by dragging or pressing number keys). In other words, researching decreases usability. So, instead of changing maximum level, how about changing bonus value from 2 to 1 in level 23 and higher, so that at max level you would get 65 slots? And logistic trash slots are not required as many, so the bonus is 1 from level 20, making total be 50. In this way, the inventory window fits nicely and the top column of toolbelt is (barely) accessible, even if toolbelt 2 is researched (not counting Bob's toolbelt 3 and forth).

![image](https://cloud.githubusercontent.com/assets/2798715/16937818/3a3b5f4c-4d40-11e6-831b-725b87ab0eb4.png)

After all, it should be hard to gain benefit from already well-researched technology. Since we've already decreased the value from 5 to 2 at level 6, it won't bother players, right?

**Comment by OvermindDL1** [comment]
I'd definitely say shorten it then, and make them more expensive faster.

**Comment by msakuta** [comment]
OK, I rebalanced so that logistic count is maxed at 70 and logistic trash count 45, because you'd want more logistic slots than trash slots. Also changed the base of exponent to make them substantially more expensive.

![image](https://cloud.githubusercontent.com/assets/2798715/16974228/79a03f40-4e08-11e6-80a6-8f7c358b2bfc.png)

![image](https://cloud.githubusercontent.com/assets/2798715/16974343/b4267584-4e09-11e6-8bd0-2288efd2cfbb.png)

**Comment by OvermindDL1** [comment]
Looks awesome.
